---
- debug:
    msg: "Checking disk {{ disk }}"

- name: Check if hard drive is formatted for Linux LVM
  shell: "fdisk -l {{ disk }} | grep 8e"
  register: lvm_check
  ignore_errors: true

- debug:
    msg: "Disk was already formatted for use in Linux LVM"
  when: lvm_check.stdout != ''

- name: Format hard drive for Linux LVM
  parted:
    device: "{{ disk }}"
    flags: [ lvm ]
    state: present
    number: 1
  when: lvm_check.stdout == ''

- name: Prepare formatted device for LVM
  shell: "pvcreate {{ disk }}1"
  args:
    creates: "{{ disk }}1"
  register: lvm_prepare
  when: lvm_check.stdout == ''
